---
- hosts: {{ instance_name }}
  connection: ssh
  user: ubuntu
  sudo: yes
  gather_facts: no
  tasks:

  vars:
    - tenant_message: "{{ tenant_message }}"
  
#  - name: Write message
#    shell: echo "{{ tenant_message }}" > /var/tmp/index.html
#
#  - name: setup s1u interface config
#    shell: ./start_3gpp_int.sh eth1 {{ s1u_sgw_tag }} {{ s1u_sgw_ip }}/24
#
#  - name: setup s11 interface config
#    shell: ./start_3gpp_int.sh eth2 {{ s11_sgw_tag }} {{ s11_sgw_ip }}/24
#
#  - name: setup s5s8 interface config
#    shell: ./start_3gpp_int.sh eth3 {{ s5s8_sgw_tag }} {{ s5s8_sgw_ip }}/24
  
#  roles:
#    - install_apache
#    - create_index

